#!/bin/bash

echo "🔄 FinSpeak Service Restart Script"
echo "=================================="
echo ""
echo "This script will help you restart the backend server."
echo "The frontend will automatically detect changes."
echo ""
echo "📋 Instructions:"
echo "1. Stop the current backend server (press Ctrl+C in the terminal running server.py)"
echo "2. Run this command:"
echo ""
echo "   cd /Users/karvendh/Projects/FinSpeak/backend && python server.py"
echo ""
echo "3. Test by asking: 'Show me my loans' or 'What's my credit card status?'"
echo ""
echo "✅ Expected: Loans and credit cards will appear in beautiful colored boxes"
echo ""
echo "=================================="
